modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="resource_generator"
version="1.0.0"
displayName="Resource generator"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Guest, MCreator"

[[dependencies.resource_generator]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




